# product-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product-service  # Define the namespace here
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer