# product-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: product-service  # Define the namespace here
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 80 #port exposed by the service 
      targetPort: 8080 #This is the port on the backend Pods to which the Service forwards traffic 
  type: LoadBalancer