# user-service-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  namespace: user-service   # Define the namespace here
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ala264/user-service:${{ github.sha }}
        ports:
        - containerPort: 8080  #Defines the port on which the container is exposed inside the Pod 
