# user-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user-service  # Define the namespace here
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80 #port exposed by the service
      targetPort: 8080 #This is the port on the backend Pods to which the Service forwards traffic 
  type: LoadBalancer