# user-service-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: user-service  # Define the namespace here
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer