name: Product Service CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ecommerce-app/product-service
          npm install

      - name: Run tests
        run: |
          cd ecommerce-app/product-service
          npm test

      - name: Build Docker image
        run: |
          cd eccomerce-app/product-service
          docker build -t ala264/product-service:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push ala264/product-service:latest
