name: Product Service CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ecommerce-app/product-service
          npm install

      - name: Run tests
        id: npm-test
        run: |
          cd ecommerce-app/product-service
          npm test

      - name: Rollback (if tests fail)
        if: failure() && steps.npm-test.outcome == 'failure' 
        run: |
          echo "Tests failed. Reverting to the previous commit..."
          git config --global user.email "hathaull@sfu.ca"
          git config --global user.name "hathaull"
          git stash save "Stashing changes before revert"
          git revert --no-edit HEAD
          git checkout HEAD^^ -- .
          git add .
          git commit -m "Restore files after reverting commit"
          git push origin main  

      - name: Build Docker image
        if: success()
        run: |
          cd ecommerce-app/product-service
          docker build -t ala264/product-service:latest .

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: success()
        run: |
          docker push ala264/product-service:latest
