name: User Service CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd ecommerce-app/user-service
          npm install

      - name: Run tests
        id: npm-test
        run: |
          cd ecommerce-app/user-service
          npm test

      - name: Rollback (if tests fail)
        if: failure() && steps.npm-test.outcome == 'failure' 
        run: |
          echo "Tests failed. Reverting to the previous commit..."
          git config --global user.email "hathaull@sfu.ca"
          git config --global user.name "hathaull"
          git stash save "Stashing changes before reset"
          git fetch --unshallow
          git reset --hard HEAD~1
          git push origin main --force

      - name: Build Docker image
        if: success()
        run: |
          cd ecommerce-app/user-service
          docker build -t ala264/user-service:${{github.sha}} .
          docker tag ala264/user-service:${{ github.sha }} ala264/user-service:latest

      - name: Log in to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        if: success()
        run: |
          docker push ala264/user-service:${{ github.sha }}
          docker push ala264/user-service:latest

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Install GKE Auth Plugin
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Configure kubectl with gcloud
        run: |
          export CLOUDSDK_CORE_PROJECT=cicd-pipeline-442500
          export CLOUDSDK_COMPUTE_REGION=us-central1
          export CLOUDSDK_CONTAINER_CLUSTER=ecommerce-cluster
          gcloud container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER \
            --region $CLOUDSDK_COMPUTE_REGION --project $CLOUDSDK_CORE_PROJECT

      - name: Verify kubectl version
        run: kubectl version --client

      - name: Ensure Namespace Exists
        run: |
          kubectl create namespace user-service || echo "Namespace already exists"

      - name: Debug List Deployments
        run: |
          kubectl get deployments --namespace=user-service

      - name: Debug Describe Deployment
        run: |
          kubectl describe deployment user-service-deployment --namespace=user-service || echo "Deployment not found"

      - name: Debug List Pods
        run: |
          kubectl get pods --namespace=user-service

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f ecommerce-app/k8s/user-service/deployment.yaml --namespace=user-service

      - name: Get External IP of User Service
        run: |
          echo "Waiting for the LoadBalancer IP to be assigned..."
          
          # Initial delay for load balancer IP assignment
          sleep 30  # Wait for 30 seconds to give time for the LoadBalancer to be provisioned
          
          # Fetch the external IP of the user-service
          EXTERNAL_IP=$(kubectl get svc user-service --namespace=user-service -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
          
          # Retry logic in case the IP is not assigned yet
          if [ -z "$EXTERNAL_IP" ]; then
            echo "External IP not assigned yet, retrying every 10 seconds..."
            for i in {1..10}; do
              echo "Checking... attempt $i"
              EXTERNAL_IP=$(kubectl get svc user-service --namespace=user-service -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
              if [ -n "$EXTERNAL_IP" ]; then
                echo "External IP found: $EXTERNAL_IP"
                break
              fi
              sleep 10  # Wait for 10 seconds before checking again
            done
          fi
          
          # If we have an external IP, print it; otherwise, notify failure
          if [ -n "$EXTERNAL_IP" ]; then
            echo "External IP of user-service: $EXTERNAL_IP"
          else
            echo "Failed to retrieve external IP after 10 attempts."
            exit 1  # Exit with an error if IP is not found
          fi




      - name: Update Kubernetes Deployment
        if: success()



